name: Rime Cantonese compilation check

on:
  # Trigger the workflow on push or pull request,
  # but only for the dev and main branches
  push:
    branches:
      - main
      - trunk
  pull_request:
    branches:
      - main
      - trunk
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - run: | 
          echo "Installing rime engine"
          sudo apt-get install curl git ibus-rime -y
      - run: | 
          echo "Installing rime-cantonese files"
          curl -fsSL https://git.io/rime-install | bash -s -- :preset emoji CanCLID/rime-loengfan sgalal/rime-opencc-latest custom:set:config=default,key=installed_from,value=rime-cantonese custom:add:schema=jyut6ping3 lotem/rime-octagram-data lotem/rime-octagram-data@hant lotem/rime-octagram-data:customize:schema=jyut6ping3,model=hant
          cp ./*.yaml ~/.config/ibus/rime
          cp ./opencc/* ~/.config/ibus/rime
      - run: | 
          echo "Compiling..."
          chmod u+wx ~/.config/ibus/rime/*
          rime_deployer --build ~/.config/ibus/rime 2> log.tmp
      - run: |
          echo "Checking..."
          cat log.tmp
          exit $( cat log.tmp | grep -c ^[EW] ) 

  check_jyutping:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - run: |
          echo "Building checker from source..."
          g++ .ci/checker.cpp -o checker.o -Ofast
          chmod u+x ./checker.o
      - run: |
          echo "Checking jyut6ping3.dict.yaml"
          ./checker.o jyut6ping3.dict.yaml
